name: Ruby

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.0'
          - '2.7'
          - '2.6'
          - jruby
        rails:
          - rails_7.0
          - rails_6.1
          - rails_6.0
          - rails_5.2
          - rails_5.1
          - rails_5.0
        exclude:
          - ruby: '2.6'
            rails: rails_7.0

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.rails }}.gemfile

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Build and test with Rake
        run: bundle exec rake
